"""Domain-agnostic forecast ensembling and calibration core.

Specialized layers (e.g. the general-question forecaster in ``forecaster/``)
import from here; this package never imports specialized code.

Full documentation: [DOCUMENTATION.md](DOCUMENTATION.md) (prompts 18 + 19 + 21 + 23).
Bayesian formation: [BAYESIAN_DOCUMENTATION.md](BAYESIAN_DOCUMENTATION.md) (prompt 24).
Supervisor details: [SUPERVISOR_DOCUMENTATION.md](SUPERVISOR_DOCUMENTATION.md).
Uncertainty details: [UNCERTAINTY_DOCUMENTATION.md](UNCERTAINTY_DOCUMENTATION.md).
Leakage judge: [LEAKAGE_JUDGE_DOCUMENTATION.md](LEAKAGE_JUDGE_DOCUMENTATION.md).
"""

from core.forecast.agentic_search import (
    AgenticAsOfSearcher,
    BedrockQueryPlannerLLM,
    FixtureQueryPlanner,
    QueryPlan,
    QueryPlannerLLM,
    rank_evidence,
)
from core.forecast.bayesian import (
    BayesianEnsembleResult,
    BedrockEvidenceLikelihoodLLM,
    EvidenceLikelihoodLLM,
    FixtureEvidenceLikelihoodLLM,
    LikelihoodDraw,
    LikelihoodRequest,
    Posterior,
    build_bayesian_ensemble,
    build_likelihood_requests,
    elicit_and_build_bayesian_ensemble,
    posterior,
)
from core.forecast.cache import EnsembleCache, EnsembleCacheKey, InMemoryEnsembleCache
from core.forecast.calibration import (
    DEFAULT_ALPHA,
    DEFAULT_BOUNDARY_MARGIN,
    DEFAULT_SPREAD_THRESHOLD,
    CalibratedForecast,
    calibrate,
    calibrate_ensemble,
    near_decision_boundary,
)
from core.forecast.ensemble import (
    DEFAULT_TRIM_FRACTION,
    Aggregator,
    EnsembleForecast,
    aggregate,
    build_ensemble,
    build_ensemble_config,
    ensemble_std,
)
from core.forecast.leakage_judge import (
    BedrockLeakageJudgeLLM,
    FixtureLeakageJudgeLLM,
    LeakageJudge,
    LeakageJudgeLLM,
    LeakageReport,
    LeakageVerdict,
    QuarantineRecord,
    RegistrySlice,
    Trace,
    TraceComponent,
    audit_and_quarantine,
    trace_from_ensemble,
    trace_from_supervisor,
)
from core.forecast.leakage_validation import ValidationReport, validate_judge
from core.forecast.llm import (
    BedrockForecastLLM,
    FixtureForecastLLM,
    ForecastDraw,
    ForecastLLM,
    ForecastRequest,
)
from core.forecast.search import AsOfSearcher, Evidence, FixtureAsOfSearch
from core.forecast.supervisor import (
    DEFAULT_MIN_CLUSTER_SIZE,
    DEFAULT_MULTIMODAL_GAP,
    DEFAULT_OUTLIER_STD_MULTIPLIER,
    SUPERVISOR_PROMPT_VERSION,
    BedrockSupervisorLLM,
    Confidence,
    Disagreement,
    DisagreementKind,
    FixtureSupervisorLLM,
    FixtureSupervisorResponse,
    InMemoryReconciliationCache,
    ReconciledForecast,
    ReconciliationCache,
    ReconciliationCacheKey,
    ReconciliationProposal,
    Supervisor,
    SupervisorLLM,
    build_resolution_query,
    build_supervisor_config,
    detect_disagreement,
    reconciliation_to_audit_dict,
)
from core.forecast.uncertainty import (
    DEFAULT_HAIRCUT_SENSITIVITY,
    Uncertainty,
    UncertaintyConfig,
    apply_stability_haircut,
    combine_uncertainty,
    event_uncertainty,
    llm_output_uncertainty,
    quantify_from_calibrated,
    quantify_from_ensemble,
    quantify_uncertainty,
    stability_haircut,
)

__all__ = [
    "AgenticAsOfSearcher",
    "BayesianEnsembleResult",
    "BedrockEvidenceLikelihoodLLM",
    "BedrockForecastLLM",
    "BedrockLeakageJudgeLLM",
    "BedrockQueryPlannerLLM",
    "BedrockSupervisorLLM",
    "EvidenceLikelihoodLLM",
    "FixtureEvidenceLikelihoodLLM",
    "LikelihoodDraw",
    "LikelihoodRequest",
    "Posterior",
    "DEFAULT_ALPHA",
    "DEFAULT_BOUNDARY_MARGIN",
    "DEFAULT_MIN_CLUSTER_SIZE",
    "DEFAULT_MULTIMODAL_GAP",
    "DEFAULT_OUTLIER_STD_MULTIPLIER",
    "DEFAULT_SPREAD_THRESHOLD",
    "DEFAULT_TRIM_FRACTION",
    "DEFAULT_HAIRCUT_SENSITIVITY",
    "SUPERVISOR_PROMPT_VERSION",
    "Aggregator",
    "AsOfSearcher",
    "CalibratedForecast",
    "Confidence",
    "Disagreement",
    "DisagreementKind",
    "EnsembleCache",
    "EnsembleCacheKey",
    "EnsembleForecast",
    "Evidence",
    "FixtureAsOfSearch",
    "FixtureLeakageJudgeLLM",
    "FixtureForecastLLM",
    "FixtureQueryPlanner",
    "FixtureSupervisorLLM",
    "FixtureSupervisorResponse",
    "ForecastDraw",
    "ForecastLLM",
    "ForecastRequest",
    "InMemoryEnsembleCache",
    "InMemoryReconciliationCache",
    "LeakageJudge",
    "LeakageJudgeLLM",
    "LeakageReport",
    "LeakageVerdict",
    "QuarantineRecord",
    "QueryPlan",
    "QueryPlannerLLM",
    "RegistrySlice",
    "Trace",
    "TraceComponent",
    "ValidationReport",
    "ReconciledForecast",
    "ReconciliationCache",
    "ReconciliationCacheKey",
    "ReconciliationProposal",
    "Supervisor",
    "SupervisorLLM",
    "Uncertainty",
    "UncertaintyConfig",
    "aggregate",
    "apply_stability_haircut",
    "audit_and_quarantine",
    "build_bayesian_ensemble",
    "build_ensemble",
    "build_ensemble_config",
    "build_likelihood_requests",
    "elicit_and_build_bayesian_ensemble",
    "posterior",
    "build_resolution_query",
    "build_supervisor_config",
    "calibrate",
    "calibrate_ensemble",
    "combine_uncertainty",
    "detect_disagreement",
    "ensemble_std",
    "rank_evidence",
    "event_uncertainty",
    "llm_output_uncertainty",
    "near_decision_boundary",
    "quantify_from_calibrated",
    "quantify_from_ensemble",
    "quantify_uncertainty",
    "reconciliation_to_audit_dict",
    "stability_haircut",
    "trace_from_ensemble",
    "trace_from_supervisor",
    "validate_judge",
]
